# The scripts in `./pi` are meant to run on a Raspberry Pi with a connected and configured Pi Camera. 

.PHONY: run-tcp run-zmq

run-tcp:
	python3 camera_tcp_client.py

run-zmq:
	python3 camera_zmq_client.py